API_KEY = 'ypzk8WBmm1ZlHFx1CVSW5c4U0'
API_SECRET_KEY = 'ldyAiwqEX0XvRxnwqo1scEN8Bd2txSAoK6TQt8VwC4fEL4MdFR'
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAByLTgEAAAAAascsmPeECsitPKHRVkM5X4JMF8Y%3DCMHvDeOr4VuI7PYnWfY5JmsPAJZnwr6NUpgC972yZkiYQI0lCo'

ACCESS_TOKEN = '2984320970-ZDXuYGUThRnRy3ssnGZnMfSdiOEQ0gkL47hZpCQ'
ACCESS_TOKEN_SECRET = 'fDaGyRmTUGKYr04NqwI8aGWWhsoyxEy2gWq1bhfw2bp9Z'

DB_HOST = 'localhost'
DB_USER = 'soorajbharadwaj'
DB_PASSWORD = 'aruba'
DB_NAME = 'twitter_raw'
